### ISSUE TITLE
Error not explicit when time missing

### ISSUE THREAD

**Issue by SamGG** [RGLab/flowViz#29]
Hi, FYI, Best.

```r
> xyplot(GvHD[[1]][,3:7])
Error in if (!(time %in% colnames(expr))) stop("Invalid name of variable (",  : 
  argument is of length zero
```

**Comment by mikejiang** [comment]
Feel free to try out https://github.com/RGLab/ggcyto since flowViz will be phased out eventually.

**Comment by SamGG** [comment]
Thanks for the fix. I'll try ggcyto when I'll get less busy. I saw the outputs that are attractive.
