### ISSUE TITLE
WARNINGS in Linux build causing problems with Travis CI

### ISSUE THREAD

**Issue by lmweber** [RGLab/flowViz#32]
Hi, I have been having some issues with Travis CI for my package `diffcyt`, which I think are due to some of the WARNINGS from the Linux build for `flowViz`, which is installed as a dependency.

The problem is that Travis CI treats warnings as errors by default, and this behavior can't be changed with respect to installation of dependency packages, so it refuses to install `flowViz`.

I checked the warnings on the Bioconductor build report for `flowViz`, and it looks like this one is the main problem, which then also shows up in my Travis CI log. This looks like possibly quite a minor issue due to some incorrect syntax in one of the `.Rd` files:

```
Found the following significant warnings:
  Warning: /home/biocbuild/bbs-3.10-bioc/meat/flowViz/man/dot-xyplot.flowSet.Rd:5: unknown macro '\item'
  Warning: /home/biocbuild/bbs-3.10-bioc/meat/flowViz/man/dot-xyplot.flowSet.Rd:15: unknown macro '\item'
```

Is this a known issue, and/or possibly something that could be fixed for the next Bioconductor release?

(It isn't causing any problems for end users, since everything is still passing on the Bioconductor builds, but it would be great if we could get Travis CI working again for our testing. I think it is affecting both `diffcyt` and `CATALYST`, since these depend on `flowViz` via `FlowSOM`.) Thanks!

**Comment by jacobpwagner** [comment]
Hi @lmweber . This may actually already be fixed by c71d74d9d952c9289c95a18e8d18f1fe811909ce, which I just haven't merged over to bioconductor yet. I'll verify that and merge it over so hopefully in the next day or two this should resolve.

**Comment by lmweber** [comment]
Great, thanks for replying so quickly!

**Comment by jacobpwagner** [comment]
Alright. a4d37cefae10c4942db7f2c0e7f491541d79edbf should fix it (no more warnings from `R CMD CHECK`, just 6 notes) and I pushed that to bioconductor with a version bump. I might have missed today's build, but it should be good to go soon. Let me know if there are any more issues.

**Comment by lmweber** [comment]
Great, I'll check the build reports over the next couple of days, and let you know if there are any more issues.

**Comment by lmweber** [comment]
All good now, my Travis CI builds are showing up green again. Thanks again!
