### ISSUE TITLE
Is it possible to add a tag to allow the use of conda skeleton cran (and thus use the package in a conda environment)?

### ISSUE THREAD

**Issue by mcmk3** [RGLab/flowViz#33]
As above, if not inconvenient, would it be possible to add a tag to this repository?

I am trying to install Phenoflow, which has no conda package in a conda environment. It does not accept the bioconductor version of this package, so I am attemting to use conda skeleton cran 'this repository url' followed by conda build to build this package with a name that Phenoflow will accept. 
However, conda skeleton cran does not accept untagged repositories as discussed here: https://github.com/conda/conda/issues/6674.

Thank you!

**Comment by mikejiang** [comment]
done.

https://github.com/RGLab/flowViz/releases/tag/1.0

**Comment by mcmk3** [comment]
Thank you!
